FROM ubuntu:14.04
MAINTAINER Aditya Vaja <aditya.vaja@bigswitch.com>

RUN apt-get update
RUN apt-get upgrade -y --no-install-recommends
RUN apt-get install -y build-essential
RUN apt-get install -y git
RUN apt-get install -y python
RUN apt-get install -y python-dev
RUN apt-get install -y python-pip
